components/DatasetSelector.js
https://fjelltopp.atlassian.net/browse/NAV-112
=> Nav 112 better dataset selector

pages/index.js
https://fjelltopp.atlassian.net/browse/NAV-138
=> NAV-138-better-helperUrlsComponent

pages/login.js, styles/globals.css
1. username and password fields are now mandatory
2. correctly using html `<form>` input, so hitting the enter button will submit the form
3. fixed username field from `type=email` to `type=text`
4. Made auth error more user friendly (copied it from ADR)
| before                                                                                                         | after                                                                                                          |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/2634482/142900715-f434bc3e-a2d9-4aed …
=> Nav 113 better login page error handling

components/DatasetSelector.js
https://fjelltopp.atlassian.net/browse/NAV-146
=> NAV-146-close-dataset-selector-on-change

styles/globals.css
https://fjelltopp.atlassian.net/browse/NAV-147
=> NAV-147-add-scroll-to-dataset-selector

components/AuthWrapper.js, pages/login.js, pages/logout.js
https://fjelltopp.atlassian.net/browse/NAV-162
Replaced all nextjs router code with vanilla js `window.location.href = x`
=> NAV-162-hotfix-nextjs-router-issues

pages/index.js
https://fjelltopp.atlassian.net/browse/NAV-170
=> NAV-170-fix-bad-background-color-on-links

Dockerfile, package.json
https://fjelltopp.atlassian.net/browse/NAV-116
=> NAV-116-navigator-ui-in-production-mode

components/ActionButtons.js, components/DatasetSelector.js, components/LogsComponent.js, components/Sidebar.js, pages/index.js, pages/login.js, pages/tasks.js
- https://fjelltopp.atlassian.net/browse/NAV-175
- Updated code as per https://www.reactjstutorials.com/react-basics/27/react-map-and-keys
=> NAV-175-update-maps-to-having-a-valid-key

components/AuthWrapper.js, pages/_app.js, pages/no_datasets.js
https://fjelltopp.atlassian.net/browse/NAV-164
=> NAV-164-no-datasets-error-page

styles/globals.css
- https://fjelltopp.atlassian.net/browse/NAV-196
- Decreased the font-size globally by 10%
=> NAV-196: decrease font sizes

pages/index.js
https://fjelltopp.atlassian.net/browse/NAV-197
=> NAV-197-only-show-alerts-if-isLatestTask

components/Sidebar.js, package.json, pages/index.js, pages/tasks.js, yarn.lock
- https://fjelltopp.atlassian.net/browse/NAV-205
- Note: This feature reintroduces the nextjs router which we have had issues with in the past when deploying to production. So please make sure this is tested in different environments to confirm it works ok
=> NAV-205-preview-tasks-from-tasks-page

pages/tasks.js
- https://fjelltopp.atlassian.net/browse/NAV-225
- Looks like the progress bar value was never implemented 😂
=> NAV-225-fix-tasks-page-progress

components/AuthWrapper.js, package-lock.json, package.json, pages/_app.js, yarn.lock
- https://fjelltopp.atlassian.net/browse/NAV-130
- Stores the last accessed dataset in a cookie so that you can return to it easily
- There's also validation to make sure the cookie value is never null or invalid
=> NAV-130-save-currentDatasetId-in-cookie

components/MilestonesSidebar.js, lib/api.js, pages/index.js
- https://fjelltopp.atlassian.net/browse/NAV-221
- https://youtu.be/EaHXJttKn30
=> NAV-221-clickable-milestones

components/Sidebar.js, pages/tasks.js, styles/globals.css
- https://fjelltopp.atlassian.net/browse/NAV-224
- Updated hyperlinks to clickable bootstrap list items
- Made page content 100% width
- Added more padding between checkboxes and text labels
- Automatically expand the current active milestone
- Removed WIIP badge
=> NAV-224-tasklist-ui-formatting-updates

pages/tasks.js
- https://fjelltopp.atlassian.net/browse/NAV-228
- https://youtu.be/FH02WABgHeU
- There's an annoying double loading throbber which I can't seem to debug quickly. An additional jira ticket has been made to look into it in the future: https://fjelltopp.atlassian.net/browse/NAV-231
=> NAV-228-refresh-tasklist-on-pageload

components/ErrorComponents.js, pages/contact_us.js, pages/index.js
=> NAV-233-better-error-logging

components/ActionButtons.js, pages/index.js
- https://fjelltopp.atlassian.net/browse/NAV-186
- Video: https://fjelltopp.slack.com/archives/C02JHQEP623/p1639670261001500?thread_ts=1639669759.000700&cid=C02JHQEP623
=> NAV-186-async-complete-button

components/ErrorComponents.js, pages/tasks.js
- https://fjelltopp.atlassian.net/browse/NAV-237
- remove full page blocking error and loading banners and made the page load/error async without blocking the entire page
=> NAV-237-better-loading-and-erroring-on-taskspage

Jenkinsfile.build
Can be merged right after the approve.
=> NAV-174 Disable successful build notification on slack

components/LoadingBanner.js, components/LoadingComponent.js, package-lock.json, package.json, pages/_app.js, pages/index.js, styles/globals.css, yarn.lock
- https://fjelltopp.atlassian.net/browse/NAV-235
- Implements partial loading of page content to avoid the entire page blocking while any http request is being made
- Video https://youtu.be/zsaIvKWdKvw
=> NAV-235-non-fullpage-blocking-loading

components/ErrorComponents.js, lib/api.js
- [NAV-236-more-informative-error-messages](https://fjelltopp.atlassian.net/browse/NAV-236)
=> NAV-236-more-informative-error-messages

components/ActionButtons.js, lib/actionButtons.js, lib/actionButtons.test.js
- https://fjelltopp.atlassian.net/browse/NAV-185
=> NAV-185-disabled-action-button-tooltips

lib/actionButtons.js, lib/actionButtons.test.js, pages/tasks.js
- https://fjelltopp.atlassian.net/browse/NAV-227
=> NAV-227-view-future-tasks

components/ActionButtons.js, pages/index.js
- https://fjelltopp.atlassian.net/browse/NAV-206
- Only show `<Alert />` messages if you have interacted with the action buttons
=> NAV-206-hide-alerts-on-first-load

sentry.client.config.js, sentry.server.config.js
- https://fjelltopp.atlassian.net/browse/NAV-260
=> NAV-260-add-unaids-to-sentry-config

sentry.client.config.js, sentry.server.config.js
- https://fjelltopp.atlassian.net/browse/NAV-261
- Example of error thrown from my `local` env: https://sentry.io/organizations/fjelltopp/issues/3047018921/?project=6077337&query=is%3Aunresolved
=> NAV-161-add-env-to-sentry

locales/en/messages.po, locales/fr/messages.po, locales/pt/messages.po
- https://fjelltopp.atlassian.net/browse/NAV-263
- Looks like the translation `.po` files needed updating to fix this
=> NAV-263-fix-missing-translations

components/AuthWrapper.js, locales/en/messages.po, locales/fr/messages.po, locales/pt/messages.po, pages/_app.js, pages/user_not_found_in_adr.js
NAV-275 Very crude way of informing user that have never logged into ADR before to log before using Navigator
=> NAV-275 Navigator fails after login with auth0 if user hasn't logged in to ADR first

lingui.config.js, locales/config.js, locales/en/messages.po, locales/fr/messages.po, locales/pt/messages.po
I have updated our configs and extracted new po files for French and Portuguese translations to be added (creating new Jira tickets for those).
Overwrites changes in #83 which got merged somehow without anybody clicking merge?!
=> NAV-275 update internationalisation files 

locales/fr/messages.po
French translations:
- 2 drafts reviewed twice
- One last review tomorrow in the morning (final)
Should be fine already, last review will be for new eyes in the morning
update:
final version commit pushed.
=> Nav 281 translate latest po file for fr

locales/config.js
Turns french translations on now that we have @A-Souhei's PR merged.
=> NAV-279 Update translation for latest navigator_ui changes
